name: Setup

description: Setup Node.js, cache and install dependencies (using yarn specificly)

inputs:
  node_version:
    description: Node.js version
    required: false
    default: "14"

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup git user to "anakmagang"
      shell: bash
      run: git config user.email "anakmagang@evilfactorylabs.org" && git config user.name "anakmagang"

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: ${{ inputs.node_version }}

    - name: yarn install
      shell: bash
      run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline
