name: Setup

description: Setup Node.js, cache and install dependencies (using yarn specificly)

inputs:
  node_version:
    description: Node.js version
    required: false
    default: "20"
  rust_cache_enable:
    description: enable actions/cache@v3 for rust
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user to "anakmagang"
      shell: bash
      run: |
        git config user.email "anakmagang@evilfactorylabs.org"
        git config user.name "anakmagang"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ inputs.node_version }}

    - name: rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: wasm32-wasi

    - name: yarn install
      shell: bash
      run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline || yarn install --check-cache

    - uses: actions/cache@v3
      id: "rust_cache_hits"
      if: ${{ inputs.rust_cache_enable }}
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          /usr/share/rust/.rustup
          **/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
