name: release
on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - name: validate (lint)
        run: yarn lint
  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - name: run test
        run: yarn test --collectCoverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: test run generator API markdown
        run: .husky/generate-api-md

  release:
    needs:
      - validate
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.2
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main', 
              'next', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semrel-extra/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
