name: release
on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline
      - name: Check commit message
        uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.2
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main', 
              'next', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semrel-extra/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
